version: '3'
services:
 website:
  image: php:apache
  ports:
  - "80:80"
  environment:
   USERNAME: toto
   PASSWORD: python
  volumes:
   - "./website:/var/www/html"
  depends_on:
   - API
  restart: always
 API:
  image: mystudentlist
  ports :
   - "5000:5000"
  volumes:
   - "./simple_api/data:/data"
  restart: always

